#!/bin/sh
set -e
umask 022
dir=libvna-windows-x86_64 
git clone https://github.com/yaml/libyaml.git
( cd libyaml
    ./bootstrap
    ./configure "--prefix=/ucrt64"
    make install )
mkdir "/tmp/${dir}"
./bootstrap
./configure "--prefix=/tmp/${dir}" "LDFLAGS=-static-libgcc"
make -j10 install
cp /ucrt64/bin/libyaml*.dll "/tmp/${dir}/bin/"
( cd /tmp && zip "${dir}" "${dir}" )
mv /tmp/${dir}.zip .
