name: Make Release
on:
  push:
    tags: [ "v[0-9]*" ]

jobs:
  build:
    name: Build assets for ${{matrix.buildplat.sys}} ${{matrix.buildplat.arch}}
    strategy:
      matrix:
        buildplat:
        - { sys: macos-latest, arch: test_arch }
        # - { sys: ubuntu-22.04, arch: x86_64 }
        # - { sys: windows-2019, arch: x86_64 }
      fail-fast: true
    runs-on: ${{ matrix.buildplat.sys }}
    steps:
    - name: Prepare git
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Build Debian Package (Linux)
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt-get update
        sudo apt-get install autoconf automake build-essential \
             debhelper-compat devscripts libtool libyaml-dev make
        ./bootstrap
        ./configure
        make -j10 deb
    - name: Upload Artifacts (Linux)
      if: ${{ runner.os == 'Linux' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.buildplat.sys }}-${{ matrix.buildplat.arch }}
        path: |
          libvna-*.tar.gz
          deb/*.deb
          deb/*.dsc
          deb/*.buildinfo
    - name: Setup MSYS2
      if: ${{ runner.os == 'Windows' }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: mingw-w64-ucrt-${{matrix.buildplat.arch}}-gcc
                 mingw-w64-ucrt-${{matrix.buildplat.arch}}-ghostscript
                 autoconf automake git groff make libtool pkg-config zip
    - name: Build Libvna (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: msys2 {0}
      run:
        bash .github/tools/build-windows
    - name: Upload Artifacts (Windows)
      if: ${{ runner.os == 'Windows' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.buildplat.sys }}-${{ matrix.buildplat.arch }}
        path: libvna-windows-x86_64.zip
    - name: Build Artifact (Test)
      if: ${{ runner.os == 'macOS' }}
      run: |
        brew install --build-bottle --formula libvna.rb
        brew test libvna
        brew bottle --force-core-tap libvna
        ls -l
        find `brew --prefix` -name \*libvna\*
    - name: Upload Artifacts (Mac)
      if: ${{ runner.os == 'macOS' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.buildplat.sys }}-${{ matrix.buildplat.arch }}
        path: *.bottle.tar.gz

  make_release:
    name: Make Release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Delay
      run: |
        sleep 5
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        merge-multiple: true
    - name: Check Artifacts
      run: |
        ls -R artifacts
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Assets
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["artifacts/**/*"]'
