name: Make Release
on:
  push:
    tags: [ "v[0-9]*" ]

jobs:
  build:
    name: Build assets for ${{matrix.buildplat.sys}} ${{matrix.buildplat.arch}}
    strategy:
      matrix:
        buildplat:
        - { sys: ubuntu-22.04, arch: x86_64 }
        - { sys: windows-2019, arch: x86_64 }
      fail-fast: true
    runs-on: ${{ matrix.buildplat.sys }}
    steps:
    - name: Prepare git
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Build Debian Package (Linux)
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt-get update
        sudo apt-get install autoconf automake build-essential \
             debhelper-compat devscripts libtool libyaml-dev make
        ./bootstrap
        ./configure
        make -j10 deb
    - name: Upload Artifacts (Linux)
      if: ${{ runner.os == 'Linux' }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.buildplat.sys }}-${{ matrix.buildplat.arch }}
        path: |
          libvna-*.tar.gz
          deb/*.deb
          deb/*.dsc
          deb/*.buildinfo
    - name: Setup MSYS2
      if: ${{ runner.os == 'Windows' }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: mingw-w64-ucrt-${{matrix.buildplat.arch}}-gcc
                 mingw-w64-ucrt-${{matrix.buildplat.arch}}-ghostscript
                 autoconf automake git groff make libtool pkg-config zip
    - name: Build Libvna (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: msys2 {0}
      run:
        bash .github/tools/build-windows
    - name: Upload Artifacts (Windows)
      if: ${{ runner.os == 'Windows' }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.buildplat.sys }}-${{ matrix.buildplat.arch }}
        path: libvna-windows-x86_64.zip

  make_release:
    name: Make Release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Download Assets
      run: |
        mkdir assets
        cd assets
        echo "Before:"
        ls
        gh run download "context.payload.workflow_run.id"
        echo "After:"
        ls
        echo "gitgub.ref: ${{ github.ref }}"
    - name: Upload Release Assets
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["assets/*"]'
